language: python

python:
  - "2.7"
  - "3.5"

before_install:
  - sudo apt-get update
  - sudo apt-get install libavahi-compat-libdnssd-dev

install:
  - pip install flake8

before-script:
  - flake8 .

script:
  - python -m unittest test_pybonjour.py
